### ISSUE TITLE
We should add a menu "News" at the top

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB-web#121]
Users are usually keen in reading some activity thread or release notes

**Comment by kofiav** [comment]
GitHub has a releases section https://github.com/bhklab/PharmacoDB-web/releases - it is all rather random and inconsistent right now, but I'd recommend linking to it and taking the time to be clear and transparent in what's available on each "version".

**Comment by chuntul** [comment]
Closed by 1cbddf987a3a7ab8912dfaca73ba81810dc27b15
