### ISSUE TITLE
Problem with breast tissue

### ISSUE THREAD

**Issue by bhaibeka** [bhklab/PharmacoDB-web#48]
The listed number of cell lines is not correct. For instance, CCLE contains >50 breast cancer cell lines
http://pharmacodb.pmgenomics.ca/tissues/8

**Comment by p-smirnov** [comment]
@bhaibeka It seems we have only 31 breast cell lines tested with a drug in CCLE. 

On most other plots like this we count the actual number of cells lines with experiments on them. I think its a question of clearly labeling/deciding what we want to display.

**Comment by p-smirnov** [comment]
Fixed via 8ec11a3c90384bd6499b39efc0432161bb336a44
