### ISSUE TITLE
Google Analytics may not work properly with Turbolinks

### ISSUE THREAD

**Issue by assefamaru** [bhklab/PharmacoDB-web#50]
Commit 42d0a32 introduces Google Analytics snippet in Application Layouts right before `</head>`. This might be a problem since Rails Turbolinks links/swaps the `<body></body>` of pages so that the `head` is not reloaded per page request. As is stated in [github.com/turbolinks/turbolinks](https://github.com/turbolinks/turbolinks), 

> When you follow a link, Turbolinks automatically fetches the page, swaps in its `<body>`, and merges its `<head>`, all without incurring the cost of a full page load.

Because of this, a user can follow a link and see a new page, but google analytics will think that page has not changed since a new page has not been loaded. 

Here is a possible fix:

```erb
<%# application.html.erb %>
<%# Put this code snippet between the <head></head>-tags in your application layout & %>
<%# replace 'UA-XXXXXXXX-X' with your own unique Google Analytics Tracking ID %>

<%# ... %>
<head>
  <%# ... %>
  <% if Rails.env.production? %>
    <script type="text/javascript">
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-XXXXXXXX-X', 'auto');
    </script>
  <% end %>
</head>
<%# ... %>
```
then

```coffee
# google_analytics.js.coffee
# Put this file into your assets/javascripts/ folder and assure
# it gets loaded by checking or editing your assets/javascripts/application.js
# file as appropriate

document.addEventListener 'turbolinks:load', (event) ->
  if typeof ga is 'function'
    ga('set', 'location', event.data.url)
    ga('send', 'pageview')
```
This way, we can listen to `turbolinks:load` to track pageviews instead.

**Comment by kofiav** [comment]
@assefamaru 

Thanks for checking this out. That explains why I wasn't getting any updates. Feel free to commit a fix / file a PR if it's quick.

**Comment by assefamaru** [comment]
@kofiav sure, I can push a fix, then you can test it using the google account used to set up the tracking. But make sure to change your environment check from `Rails.env.production?` to `Rails.env.development?` when testing locally, as otherwise, you will not see any activity (unless app is live in production).

**Comment by kofiav** [comment]
Great! I will definitely keep that in mind 👌

**Comment by assefamaru** [comment]
@kofiav let me know if tracking works properly, and if `google_analytics.js.coffee` is properly included in assets.

**Comment by kofiav** [comment]
Ok I'll test it out and let you know

**Comment by kofiav** [comment]
@assefamaru 

It is working now :-) 

I think we can close this issue now.

**Comment by kofiav** [comment]
@assefamaru 

Just letting you know that the Rails environment in the web server is `development` so we temporarily changed the if statement to `Rails.env.development?` to get the tracking to work.

**Comment by assefamaru** [comment]
@kofiav see me comment/question at #45.
