### ISSUE TITLE
List all uncategorized cell-lines

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#65]
![screen shot 2017-07-17 at 3 25 00 pm](https://user-images.githubusercontent.com/4621203/28285835-1ec0295e-6b04-11e7-8e15-c5e466f9378c.png)

A significant chunk of cell lines are included in the `Other` category. It would be useful to have an interactive table somewhere that lists all of these cell lines.

**Comment by p-smirnov** [comment]
@chuntul fixed in a5e2b22f984a4e28b3f3384a09f8bbc845d6cbf4
