### ISSUE TITLE
Hide plot and drugs table if no data is available

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#69]
![screen shot 2017-07-17 at 3 41 40 pm](https://user-images.githubusercontent.com/4621203/28286527-7917a3d0-6b06-11e7-910b-0a09f4908ef0.png)

Aside from the cell-line summary the only thing that should appear in this page is the molecular data.

**Comment by p-smirnov** [comment]
Will do tomorrow for all pages/tables

**Comment by p-smirnov** [comment]
Fixed in latest commit.
