### ISSUE TITLE
Order of datasets in plots should matter

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#70]
![screen shot 2017-07-17 at 3 47 05 pm](https://user-images.githubusercontent.com/4621203/28286741-358733dc-6b07-11e7-9acb-d8087e106d7e.png)

The (ascending / descending) order of the datasets in the bar plot should be in accordance to some metric.

**Comment by chuntul** [comment]
closed by 1cbddf987a3a7ab8912dfaca73ba81810dc27b15
