### ISSUE TITLE
Add a column for tissue type

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#71]
Columns in cell lines table should be `Cell line`, `Datasets`, `# Experiments`, `Tissue Type` instead of `Cell line`, `Datasets`, `# Experiments`.

![screen shot 2017-07-17 at 4 45 01 pm](https://user-images.githubusercontent.com/4621203/28289067-4d87a5e0-6b0f-11e7-9f08-3a92b2c0f0ca.png)

**Comment by assefamaru** [comment]
@kofiav wouldn't it be redundant to have the same tissue type repeated on every row of table?

**Comment by kofiav** [comment]
@assefamaru good catch, I made a mistake, the new `Tissue Type` column is supposed to be added to the `Cell lines` table not the `Drugs` table. 

@p-smirnov is probably the best person to ask if you have any further concerns about this. Most of the new feedback came from a meeting that I was unable to attend.

**Comment by assefamaru** [comment]
@kofiav sounds good. `Tissue Type` on the `cell lines` table is a good add-on.
