### ISSUE TITLE
Update About page with lab contact info

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#73]
- should contain more lab contact information
- should be transferred from `/about` to `/docs/about`

**Comment by assefamaru** [comment]
@kofiav would contact info be better placed in `/contacts` instead of `/docs/about`? I think `/docs` would be better modularized if it only contains `documentation` content.

**Comment by kofiav** [comment]
@assefamaru 

What you say makes sense and I don't disagree with it. I will just provide some context on where this is coming from.

This morning the app went under scrutiny by new users and the general consensus from what I've been told is that there should be:
- less verbosity (none of the bolded statements should contain a `Read more`)
- more info on the lab itself. It is unclear to me how this should be done. I personally think adding a `/contacts` would be rather redundant. Briefly mentioning the location and website of the lab at the bottom of the page should be sufficient.

Also people want the About page to be somehow linked to the documentation page (again it's not really set in stone how this should be done). If you can think of an elegant way this could be done it would be awesome. @p-smirnov can probably give you better reasons on the reasoning behind this decision.
