### ISSUE TITLE
colour scheme for more than 4 of the same dataset in dose/response plots

### ISSUE THREAD

**Issue by chuntul** [bhklab/PharmacoDB-web#98]
/search?q=HCC2185+17-AAG for testing

**Comment by p-smirnov** [comment]
Its back.

![azd6244-a549-ddrcpmdb_cell_drug](https://user-images.githubusercontent.com/2171645/29299691-7cd00208-813e-11e7-98f9-eb4632d91e30.png)

**Comment by chuntul** [comment]
WHY

**Comment by p-smirnov** [comment]
squashed via cb79b532fbc2098357c4d43f7ef3c4b3fef39dfc
